### ISSUE TITLE
TypeError: Cannot read property 'url' of null at cacheCurrentPage

### ISSUE THREAD

**Issue by imton** [rails/turbolinks#530]
I have a form with 4 tabs, each with history, when changed the url adds #tab1 ... #tab4
I append on "ajax:before" a remote=true form a hidden field with the anchor and send it back like this: 

My Controller

````ruby
...
format.js { redirect_to XX_path(YYY, anchor: params[:anchor]), change: 'edit-campaign-actions' }
...
````

If I load the edit form at #tab2 and I edit a field there, it will redirect me back to the same #tab2 and everything goes ok.
When I load the edit form in #tab2 move to #tab3 and the redirect goes to #tab3, I get this:

````
TypeError: Cannot read property 'url' of null
    at cacheCurrentPage (http://www.audify.io:2026/assets/dashboard.js:32256:52)
    at Object.fetch (http://www.audify.io:2026/assets/dashboard.js:32139:5)
    at eval (eval at <anonymous> (http://www.audify.io:2026/assets/dashboard.js:1746:22), <anonymous>:1:12)
    at eval (native)
    at http://www.audify.io:2026/assets/dashboard.js:1746:22
    at Function.jQuery.extend.globalEval (http://www.audify.io:2026/assets/dashboard.js:1747:7)
    at jQuery.ajaxSetup.converters.text script (http://www.audify.io:2026/assets/dashboard.js:11146:11)
    at ajaxConvert (http://www.audify.io:2026/assets/dashboard.js:10216:19)
    at done (http://www.audify.io:2026/assets/dashboard.js:10633:15)
    at XMLHttpRequest.jQuery.ajaxTransport.send.callback (http://www.audify.io:2026/assets/dashboard.js:11093:8)
````

**Comment by imton** [comment]
Forgot to add I partially solved by forking and returning 
````coffeescript
return if !cacheCurrentPage
````

**Comment by Thibaut** [comment]
Do you have a live website where we can replicate the bug?

**Comment by imton** [comment]
@Thibaut sadly not. I was using the master this repo as gem. Ask me for any info that might help.

**Comment by Thibaut** [comment]
@imton does this occur in both Chrome and Firefox?

**Comment by Thibaut** [comment]
Also, make sure you don't have code that calls `stopImmediatePropagation` in a `hashchange` event handler.

**Comment by imton** [comment]
Haven't tested it on Firefox.
Well I am using https://github.com/aidanlister/jquery-stickytabs

Gaston Morixe
Partner Black.uy

+59898704249
@_imton <http://twitter.com/_imton>

Montevideo, Uruguay

**Comment by Thibaut** [comment]
I tried my best to replicate using `jquery-stickytabs`, but wasn't able to.
Feel free to re-open if you can provide a failing test case or example code that we can use to replicate.
